controller_list:
  - name: fake_crustcrawler_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_crustcrawler_gripper_controller
    joints:
      - joint_6
      - left_finger_joint
      - right_finger_joint